name: aura_cam
description: AI Camera App
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  http: ^1.1.0
flutter:
  uses-material-design: true
