name: Build Aura Cam APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true 

      - name: Get App Ingredients
        run: flutter pub get 

      - name: Build the APK
        run: flutter build apk --debug

      - name: Upload the finished APK
        uses: actions/upload-artifact@v4 # Updated to v4! This fixes the error.
        with:
          name: aura-cam-app
          path: build/app/outputs/flutter-apk/app-debug.apk
